### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by Ashah15**

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello @Ashah15 @jucora 

You did a really great work!! There is some changes to do 

- [ ] You forgot the `lib/` folder.

- [ ] `**OPTIONAL** (for now)` : `setup` must be created from `development` branch and the PR should be **merge into `development` from `setup`**. You could solve that for the next Milestone.

Kindly make those about submit a new code review request.

**Comment by jucora** [comment]
Hello, thanks for code review, we sent the first Milestone without the lib folder because we were trying to set a empty folder but github does not allow us to do that, we were trying with .gitignore and .keep but the file was still there so we consider this is not so relevant because in next Milestone that folder should have game_logic file

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello coders,

We understand the effort you did. Thank you for that.
As it's a requirement, I mean the presence of `lib/` folder, just put a hidden file into the folder and push it back. Usually we use `.gitkeep`. 
So create that file into the `lib/` folder and push the changes.

Thanks

**Review by maelfosso — APPROVED** [review]
# Well done :+1:  :smile: 

You can merge and fill the project completion form.
Good luck with the next milestone

**`REQUIRED`**
For the next Milestone, please apply the **Git Flow** process
- You created a branch `development` from `master` using `git checkout -b development`
- Then you created the milestone branch from the `development` using `git checkout -b user_interface`

You will merge to the `development` branch into the `master` branch when all the milestone will be approved.

Thank.

**Pull request merged**
